# Generated by Django 5.1 on 2024-08-11 08:15

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(max_length=100)),
                ('member2', models.CharField(max_length=100)),
                ('member3', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('years_of_teaching', models.IntegerField()),
                ('has_master_degree', models.BooleanField(default=False)),
                ('highest_educational_attainment', models.CharField(default='Bachelor', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expertise', models.ManyToManyField(related_name='faculties', to='users.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('years_of_teaching', models.IntegerField(blank=True, null=True)),
                ('has_master_degree', models.BooleanField(default=False)),
                ('highest_educational_attainment', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_development', models.BooleanField(default=False)),
                ('database_management', models.BooleanField(default=False)),
                ('artificial_intelligence_and_machine_learning', models.BooleanField(default=False)),
                ('internet_of_things', models.BooleanField(default=False)),
                ('cybersecurity', models.BooleanField(default=False)),
                ('geographic_information_systems', models.BooleanField(default=False)),
                ('data_analytics_and_business_intelligence', models.BooleanField(default=False)),
                ('ecommerce_digital_marketing', models.BooleanField(default=False)),
                ('educational_technology', models.BooleanField(default=False)),
                ('healthcare_informatics', models.BooleanField(default=False)),
                ('game_development', models.BooleanField(default=False)),
                ('human_computer_interaction', models.BooleanField(default=False)),
                ('agricultural_technology', models.BooleanField(default=False)),
                ('smart_city_technologies', models.BooleanField(default=False)),
                ('fintechnology', models.BooleanField(default=False)),
                ('computer_networks', models.BooleanField(default=False)),
                ('software_engineering', models.BooleanField(default=False)),
                ('multimedia_graphics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculty')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfoTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=100, null=True)),
                ('member2', models.CharField(blank=True, max_length=100, null=True)),
                ('member3', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(max_length=50)),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.TimeField()),
                ('room', models.CharField(max_length=100)),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty1', to='users.faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty2', to='users.faculty')),
                ('faculty3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty3', to='users.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
