# Generated by Django 5.1 on 2024-08-13 14:16

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0007_remove_faculty_agricultural_technology_and_more'),
        ('users', '0003_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='highest_degree',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='other_expertise',
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_users', to='reco_app.faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='highest_educational_attainment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
