# Generated by Django 5.1 on 2024-08-14 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0009_remove_faculty_highest_educational_attainment_and_more'),
        ('users', '0005_rename_highest_educational_attainment_customuser_highest_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to='reco_app.faculty'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='reco_app.expertise'),
        ),
    ]
