# Generated by Django 5.1 on 2024-08-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_expertise_alter_customuser_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
