# Generated by Django 5.1 on 2024-08-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0014_remove_faculty_custom_user'),
        ('users', '0010_remove_customuser_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to='reco_app.faculty'),
        ),
    ]
