# Generated by Django 5.1 on 2024-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_mechanics', models.FloatField(default=0)),
                ('chapter_1', models.FloatField(default=0)),
                ('chapter_2', models.FloatField(default=0)),
                ('chapter_3', models.FloatField(default=0)),
                ('system_performance', models.FloatField(default=0)),
                ('oral_presentation_1', models.FloatField(default=0)),
                ('oral_presentation_2', models.FloatField(default=0)),
                ('oral_presentation_3', models.FloatField(default=0)),
                ('overall_grade', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('member1', models.CharField(default='m1', max_length=255)),
                ('member2', models.CharField(default='m2', max_length=255)),
                ('member3', models.CharField(default='m3', max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('title', models.CharField(default='NONE', max_length=255)),
                ('verdict', models.CharField(default='NONE', max_length=255)),
                ('specific_verdict', models.CharField(default='NONE', max_length=255)),
            ],
        ),
    ]
