# Generated by Django 5.1 on 2024-08-27 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_grade_comments_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='m1_QA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m1_content_organization',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m1_presentation_skills',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m2_QA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m2_content_organization',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m2_presentation_skills',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m3_QA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m3_content_organization',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='m3_presentation_skills',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='system_control',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='system_input',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='system_output',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='user_interface',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='member1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='member2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='member3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='specific_verdict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grade',
            name='verdict',
            field=models.CharField(max_length=255),
        ),
    ]
