# Generated by Django 5.1 on 2024-10-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_grade_m1_qa_grade_m1_content_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_EvaluationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mock_Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcriteria', to='users.mock_evaluationsection')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
            options={
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PreOral_Recos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='NONE', max_length=255)),
                ('recommendation', models.TextField(default='NONE')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='PreOral_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='NONE', max_length=255)),
                ('project_title', models.CharField(default='NONE', max_length=255)),
                ('grades_data', models.TextField(default='NONE')),
                ('verdict', models.CharField(blank=True, default='NONE', max_length=255, null=True)),
                ('checkbox_data', models.JSONField(default=dict)),
                ('othervalue', models.TextField(blank=True, default=None, null=True)),
                ('member1_grade', models.FloatField(default=-1)),
                ('member2_grade', models.FloatField(default=-1)),
                ('member3_grade', models.FloatField(default=-1)),
                ('recommendation', models.TextField(default='NONE')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='PreOral_EvaluationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='PreOral_Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='users.preoral_evaluationsection')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
            options={
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MockCriterionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdescriptions', to='users.mock_criteria')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Mock_Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Mock_Recos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='NONE', max_length=255)),
                ('recommendation', models.TextField(default='NONE')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Mock_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='NONE', max_length=255)),
                ('project_title', models.CharField(default='NONE', max_length=255)),
                ('grades_data', models.TextField(default='NONE')),
                ('verdict', models.CharField(blank=True, default='NONE', max_length=255, null=True)),
                ('checkbox_data', models.JSONField(default=dict)),
                ('othervalue', models.TextField(blank=True, default=None, null=True)),
                ('member1_grade', models.FloatField(default=-1)),
                ('member2_grade', models.FloatField(default=-1)),
                ('member3_grade', models.FloatField(default=-1)),
                ('recommendation', models.TextField(default='NONE')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.AddField(
            model_name='mock_evaluationsection',
            name='school_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear'),
        ),
        migrations.CreateModel(
            name='Mock_Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcheckboxes', to='users.mock_verdict')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='users.preoral_criteria')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkboxes', to='users.verdict')),
            ],
        ),
    ]
