# Generated by Django 5.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_mock_evaluationsection_schoolyear_mock_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_EvaluationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Final_Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcriteria', to='users.final_evaluationsection')),
            ],
            options={
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Final_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='NONE', max_length=255)),
                ('project_title', models.CharField(default='NONE', max_length=255)),
                ('grades_data', models.TextField(default='NONE')),
                ('verdict', models.CharField(blank=True, default='NONE', max_length=255, null=True)),
                ('checkbox_data', models.JSONField(default=dict)),
                ('othervalue', models.TextField(blank=True, default=None, null=True)),
                ('member1_grade', models.FloatField(default=-1)),
                ('member2_grade', models.FloatField(default=-1)),
                ('member3_grade', models.FloatField(default=-1)),
                ('recommendation', models.TextField(default='NONE')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Final_Recos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='NONE', max_length=255)),
                ('recommendation', models.TextField(default='NONE')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Final_Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Final_Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcheckboxes', to='users.final_verdict')),
            ],
        ),
        migrations.CreateModel(
            name='FinalCriterionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdescriptions', to='users.final_criteria')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
    ]
