# Generated by Django 5.1 on 2024-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_final_evaluationsection_final_criteria_final_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoral_evaluationsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
