# Generated by Django 5.1 on 2024-12-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_notif_personal_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='category',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
