# Generated by Django 5.1 on 2025-05-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_notif_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ext_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
