# Generated by Django 5.1 on 2024-08-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='expertise',
            field=models.CharField(default='cybersecurity', max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='highest_educational_attainment',
            field=models.CharField(default='Bachelor', max_length=100),
        ),
    ]
