# Generated by Django 5.1 on 2024-08-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0002_faculty_expertise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='agricultural_technology',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ai_ml',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='computer_networks',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='cybersecurity',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='data_analytics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='database_management',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ecommerce_digital_marketing',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='educational_technology',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='fintech',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='game_development',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='gis',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='hci',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='healthcare_informatics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='iot',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mobile_web_dev',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='multimedia_graphics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='smart_city_technologies',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='software_engineering',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='has_master_degree',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='highest_educational_attainment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='years_of_teaching',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='faculty',
            name='expertise',
            field=models.ManyToManyField(to='reco_app.expertise'),
        ),
    ]
