# Generated by Django 5.1 on 2024-08-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0004_faculty_agricultural_technology_faculty_ai_ml_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_active',
        ),
    ]
