# Generated by Django 5.1 on 2024-08-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0005_remove_faculty_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
