# Generated by Django 5.1 on 2024-08-13 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0006_faculty_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='agricultural_technology',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ai_ml',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='computer_networks',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='cybersecurity',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='data_analytics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='database_management',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='ecommerce_digital_marketing',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='educational_technology',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='fintech',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='game_development',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='gis',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='hci',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='healthcare_informatics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='iot',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mobile_web_dev',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='multimedia_graphics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='smart_city_technologies',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='software_engineering',
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.ManyToManyField(related_name='faculties', to='reco_app.expertise'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='has_master_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='highest_educational_attainment',
            field=models.CharField(default='Bachelor', max_length=100),
        ),
    ]
