# Generated by Django 5.1 on 2024-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0007_remove_faculty_agricultural_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='highest_degree',
            field=models.CharField(default='Bachelor', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='highest_educational_attainment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
