# Generated by Django 5.1 on 2024-08-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0009_remove_faculty_highest_educational_attainment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.ManyToManyField(to='reco_app.expertise'),
        ),
    ]
