# Generated by Django 5.1 on 2024-08-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0010_alter_faculty_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='reco_app.expertise'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
