# Generated by Django 5.1 on 2024-08-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0013_alter_faculty_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='custom_user',
        ),
    ]
