# Generated by Django 5.1 on 2024-08-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0015_faculty_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='reco_app.expertise'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='years_of_teaching',
            field=models.PositiveIntegerField(),
        ),
    ]
