# Generated by Django 5.1 on 2024-10-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0017_adviser_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_capstone_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
