# Generated by Django 5.1 on 2024-10-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0019_faculty_is_adviser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_adviser',
        ),
    ]
