# Generated by Django 5.1 on 2024-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0020_remove_faculty_is_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adviser',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
