# Generated by Django 5.1 on 2024-12-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0022_adviser_has_been_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='notif',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
