# Generated by Django 5.1 on 2025-05-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0023_adviser_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='years_of_teaching',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
