# Generated by Django 5.1 on 2024-08-11 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reco_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfoPOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=100, null=True)),
                ('member2', models.CharField(blank=True, max_length=100, null=True)),
                ('member3', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(max_length=50)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_adviser', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacher', to='reco_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfoTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=100, null=True)),
                ('member2', models.CharField(blank=True, max_length=100, null=True)),
                ('member3', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(max_length=50)),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco_app.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty1', to='reco_app.faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty2', to='reco_app.faculty')),
                ('faculty3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty3', to='reco_app.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.groupinfoth')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviserPOD_sched', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacherPOD_sched', to='reco_app.faculty')),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty1POD', to='reco_app.faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty2POD', to='reco_app.faculty')),
                ('faculty3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty3POD', to='reco_app.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_POD', to='scheduler_app.groupinfopod')),
            ],
        ),
    ]
