# Generated by Django 5.1 on 2024-08-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lunch_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='lunch_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.groupinfoth'),
        ),
        migrations.AlterField(
            model_name='schedulepod',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.groupinfopod'),
        ),
    ]
