# Generated by Django 5.1 on 2024-08-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_remove_schedule_created_at_schedule_lunch_break_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lunch_break',
        ),
        migrations.RemoveField(
            model_name='schedulepod',
            name='lunch_break',
        ),
    ]
