# Generated by Django 5.1 on 2024-08-16 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_remove_schedule_lunch_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfopod',
            name='title',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Day 0', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='has_been_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='day',
            field=models.CharField(default='Day 0', max_length=10),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='has_been_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedulepod',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.groupinfoth'),
        ),
        migrations.AlterField(
            model_name='schedulepod',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members_POD', to='scheduler_app.groupinfopod'),
        ),
        migrations.AlterField(
            model_name='schedulepod',
            name='title',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
