# Generated by Django 5.1 on 2024-10-03 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0016_adviser_group_name_alter_faculty_expertise_and_more'),
        ('scheduler_app', '0006_groupinfopod_school_year_groupinfoth_school_year_and_more'),
        ('users', '0018_mock_evaluationsection_schoolyear_mock_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfoMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=100, null=True)),
                ('member2', models.CharField(blank=True, max_length=100, null=True)),
                ('member3', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='None', max_length=200, null=True)),
                ('section', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_adviserMD', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacherMD', to='reco_app.faculty')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=100, null=True)),
                ('slot', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('day', models.CharField(default='Day 0', max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_been_rescheduled', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviserMD_sched', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacherMD_sched', to='reco_app.faculty')),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty1MD', to='reco_app.faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty2MD', to='reco_app.faculty')),
                ('faculty3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty3MD', to='reco_app.faculty')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members_MD', to='scheduler_app.groupinfomd')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
    ]
