# Generated by Django 5.1 on 2024-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0007_groupinfomd_schedulemd'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_locked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
