# Generated by Django 5.1 on 2024-10-05 00:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0017_adviser_school_year'),
        ('scheduler_app', '0009_remove_schedule_is_locked'),
        ('users', '0018_mock_evaluationsection_schoolyear_mock_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfoFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(blank=True, max_length=100, null=True)),
                ('member2', models.CharField(blank=True, max_length=100, null=True)),
                ('member3', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='None', max_length=200, null=True)),
                ('section', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_adviserFD', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacherFD', to='reco_app.faculty')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=100, null=True)),
                ('slot', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('day', models.CharField(default='Day 0', max_length=10)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_been_rescheduled', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adviserFD_sched', to='reco_app.faculty')),
                ('capstone_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_teacherFD_sched', to='reco_app.faculty')),
                ('faculty1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty1FD', to='reco_app.faculty')),
                ('faculty2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty2FD', to='reco_app.faculty')),
                ('faculty3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty3FD', to='reco_app.faculty')),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='members_FD', to='scheduler_app.groupinfofd')),
                ('school_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.schoolyear')),
            ],
        ),
    ]
