# Generated by Django 5.1 on 2024-10-05 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0010_groupinfofd_schedulefd'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfopod',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupinfoth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
