# Generated by Django 5.1 on 2024-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0011_groupinfopod_created_at_groupinfoth_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfopod',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
