# Generated by Django 5.1 on 2024-10-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0012_alter_groupinfopod_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.PositiveIntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.room'),
        ),
        migrations.AlterField(
            model_name='schedulefd',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.room'),
        ),
        migrations.AlterField(
            model_name='schedulemd',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.room'),
        ),
        migrations.AlterField(
            model_name='schedulepod',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.room'),
        ),
    ]
