# Generated by Django 5.1 on 2024-11-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0014_alter_groupinfoth_member1_alter_groupinfoth_member2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfofd',
            name='member1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfofd',
            name='member2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfofd',
            name='member3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfomd',
            name='member1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfomd',
            name='member2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfomd',
            name='member3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfopod',
            name='member1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfopod',
            name='member2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupinfopod',
            name='member3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
