# Generated by Django 5.1 on 2024-11-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0015_alter_groupinfofd_member1_alter_groupinfofd_member2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepod',
            name='new_sched',
            field=models.BooleanField(default=False),
        ),
    ]
