# Generated by Django 5.1 on 2024-12-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0017_schedule_new_sched_schedulefd_new_sched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulefd',
            name='room',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulemd',
            name='room',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='schedulepod',
            name='room',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
