# Generated by Django 5.1 on 2025-05-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_app', '0024_alter_faculty_highest_degree_and_more'),
        ('scheduler_app', '0018_alter_schedule_room_alter_schedulefd_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyUnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('8AM-9AM', '8AM-9AM'), ('9AM-10AM', '9AM-10AM'), ('8AM-9AM', '8AM-9AM'), ('9AM-10AM', '9AM-10AM'), ('10AM-11AM', '10AM-11AM'), ('11AM-12PM', '11AM-12PM'), ('1PM-2PM', '1PM-2PM'), ('2PM-3PM', '2PM-3PM'), ('3PM-4PM', '3PM-4PM'), ('4PM-5PM', '4PM-5PM')], default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco_app.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='FacultyUnavailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('8AM-9AM', '8AM-9AM'), ('9AM-10AM', '9AM-10AM'), ('8AM-9AM', '8AM-9AM'), ('9AM-10AM', '9AM-10AM'), ('10AM-11AM', '10AM-11AM'), ('11AM-12PM', '11AM-12PM'), ('1PM-2PM', '1PM-2PM'), ('2PM-3PM', '2PM-3PM'), ('3PM-4PM', '3PM-4PM'), ('4PM-5PM', '4PM-5PM')], default=None, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco_app.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'time_slot')},
            },
        ),
    ]
