# Generated by Django 5.1 on 2024-11-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_FAQs', '0003_review'),
        ('reco_app', '0022_adviser_has_been_replaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='A_FAQs.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco_app.faculty')),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
